### ISSUE TITLE
ERS status is obsolete

### ISSUE THREAD

**Issue by scholzj** [Deutsche-Boerse-Risk/DAVe-UI#6]
The ERS status is now obsolete and should be removed / not followed anymore. Do we want to replace it with the API status from the new health checks? I think it doesn't give the user much information, so maybe we should just remove it.

**Comment by Eddman** [comment]
@scholzj What are these health checks doing?

**Comment by Eddman** [comment]
Link to the original issue: Deutsche-Boerse-Risk/DAVe#37.

**Comment by scholzj** [comment]
There are two healt checks:
- /healthz says if the API is running (not deadlocked etc.)
- /readiness should tell if the application is serving some actual data (i.e. connected to the database etc.)

Both return HTTP 200 with plain text "ok" if everything works fine. But none of them goes to the extend of specifying whether Prisma is online and whether the loader is running etc. So I would say that for the time being we just remove the old status and don't add anything new.

**Comment by Eddman** [comment]
So we can use the first one to check if the BE is available on application start, right? If it's not available I would suggest to display empty screen telling "Service currently not available." instead of current behavior where we show the login screen as we are not able to validate the token or no token was stored in the browser. Obviously the screen can't be used to login as BE will not respond so I think it is a bug in our behavior. 

Once we have the application running and the BE stops working for any reason we anyway get an error when we try to call the BE and errors are properly handled by components so we do not need the call.

If the second  service returns an error does it mean that we will get an error once we call any `/api/v1.0/...` request? Or the result of these call will be empty? Depending on this it might be interesting to show some status...

**Comment by scholzj** [comment]
Well ... the /readiness is the call we really care about. Because without the API being ready the /api/* calls will not return anything meaningful. The /healthz basically only says that the app didn't somehow deadlocked it self. 

We would also need to test how it behaves with multiple services. Basically, Kubernetes should use these checks to avoid routing traffic to broker instances. But there might be some time window before Kubernetes remove the Pod from the Service and in that moment you might for "nok" from /readiness on instance A nebo "ok" from instances B and C.

But in principle we can implement a check like you suggest and show some error screen if the /readyness is not returning HTTP 200 "ok".

**Comment by Eddman** [comment]
> API being ready the /api/* calls will not return anything meaningful

What does it mean?

So you suggest to use `/readyness` instead of `/healthz` to check that BE is available and to show the message "Service currently not available." instead of login?

**Comment by scholzj** [comment]
Hmm, thinking about it ... it currently doesn't really return "nok" ... in the cases when it is not ready, the HTTP Server is not online - so the requests would probably timeout or return some error other error. I would need to try this. In the future, it could also happen that the requests return an HTTP error or timeout.

**Comment by Eddman** [comment]
For the meantime I've removed the ERS module.

For `/readyness` I would exactly expect 200 or any other 4xx or 5xx value so I know that the server is simply not responding and I shouldn't even try login or data requests.

If it is the case then we do not need anything else. I will call `/readyness` and if I get 200 I will show the application, otherwise we can show the message and add a timeout to try again in few seconds for instance.

As the request may take longer we can in the meantime show a message "Checking service availability" or something similar. This could be the case where the server is up-and-running but in deadlock. + we can add a timeout on UI side so we will not need to wait for HTTP read timeout that is set in minutes in almost all browsers.

**Comment by scholzj** [comment]
One more thought ... we will have more APIs to which the GUI will be connecting to ... for example the margin estimator. Also authentication will be handled outside of the API in the future. So maybe we should not build a single readiness check into the application because the situation will be more complicated soon.

**Comment by Eddman** [comment]
Closing as obsolete.
